### ISSUE TITLE
Paging issue with TabViews that are using TabView(selection: viewStore.binding(...) in Voice Over mode

### ISSUE THREAD

**Issue by aj2109** [pointfreeco/swift-composable-architecture#2339] opened 2023-08-01 08:24 UTC
### Description

Hello,

I have been trying to debug this for a while now and am completely at a loss.  We have 3 instances of TabViews using a similar setup to this:

TabView(selection: viewStore.binding(
                    get: \.currentPage,
                    send: Examplename.Action.changePage
                )) {
                   ForEachStore(...) { someStore
                        SomeView()
                        .tag(ViewStore(someStore).id)
                }
)

In all 3 of these instances, when you go into voice over mode, and you scroll slowly (not a prerequisite to replicating, but makes it happen more frequently) it will randomly throw the user back to the first page mode.  By contrast, where in the app we are using a @State variable or @Binding variable for the TabView (2 instances), this does not occur, hence me opening this issue.  

I cannot see any reason for this happening when debugging, and it works fine without Voice Over mode on, so I am hoping to hear if anyone else experiences this or has any suggestions. 

Thanks!

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

0.53.2

### Destination operating system

iOS 16 or 17

### Xcode version information

14.3 though has happened on previous versions too

**Comment by mbrandonw** [comment] 2023-08-01 15:06
Hi @aj2109, can you share a simple project that demonstrates the problem you are seeing?

And FWIW, while you may not be able to reproduce the problem with `@State`, it would be best to use `@ObservedObject` since that is what TCA uses under the hood. We often find bugs in vanilla SwiftUI that affect observable objects but not `@State`.

**Comment by mbrandonw** [comment] 2023-08-12 17:15
Hi @aj2109, I am going to close this since there hasn't been much activity. Feel free to start a [discussion](http://github.com/pointfreeco/swift-composable-architecture/discussions) if you want to share more details.

**Closed by mbrandonw** 2023-08-12 17:15 UTC
Labels: bug
