### ISSUE TITLE
2FA View not appearing in Tic-Tac-Toe demo

### ISSUE THREAD

**Issue by JOyo246** [pointfreeco/swift-composable-architecture#2207] opened 2023-06-15 17:46 UTC
### Description

When using an email with "2fa" the reducer does correctly set state..
```
-     _twoFactor: nil
+     _twoFactor: TwoFactor.State(
+       _alert: nil,
+       code: "",
+       isFormValid: false,
+       isTwoFactorRequestInFlight: false,
+       token: "deadbeef"
+     )
```

However the 2fa does not get presented.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I expect the 2fa flow to present.

### Actual behavior

The 2fa flow is not presented

### Steps to reproduce

1. Run Tic-Tac-Toe sample
2. select SwiftUI
3. enter an email that contains the chars, 2fa.
4. enter password: "password
5. select log in

### The Composable Architecture version information

0.54.1

### Destination operating system

iOS 16.4

### Xcode version information

Xcode 14.3

**Comment by sehdich** [comment] 2023-07-05 12:02
I also can reproduce the issue. What I've found out so far, it's may related to the `navigationDestination(...)` as it works as expected when presenting it via a `sheet(...)`.

**Comment by stephencelis** [comment] 2023-07-06 16:37
Looks like that demo was still using `NavigationView`, which is incompatible with `navigationDestination`. It definitely worked at some point during the nav beta, so must've been lost somehow. Should be fixed again when we merge!

**Closed** 2023-07-12 18:51 UTC
Labels: bug
