### ISSUE TITLE
Retain Cycle in Composable Architecture

### ISSUE THREAD

**Issue by Steven0351** [pointfreeco/swift-composable-architecture#194] opened 2020-06-22 03:49 UTC
**Describe the bug**
It appears that the composable architecture has a retain cycle somewhere in the code base. I noticed the issue when I was profiling my application and found memory leaks in Instruments. However, when I dug into them I found the retain cycle seemed to lie in the ComposableArchitecture code base. To sanity check myself, I ran the memory graph tool in Xcode after starting the TicTacToe game in the Examples project directory and I saw quite a few memory issues in that project as well. This is the lldb output of one of pair of nodes with retain cycles in the memory graph:
```
Printing description of $R0:
▿ Concatenate
  - downstream : Sink
  ▿ upstreamSubscription : Optional<Subscription>
    - some : Merge
  ▿ suffix : Effect<AppAction, Never>
    ▿ upstream : AnyPublisher
      ▿ box : <PublisherBox<MergeMany<Effect<AppAction, Never>>>: 0x60000362a720>
  ▿ demand : unlimited
    - rawValue : 9223372036854775808
Printing description of $R4:
Merge
```

**To Reproduce**
1. Build and run the TicTacToe example project
2. Navigate through the login and player screens
3. Begin the game
4. Run the memory graph debugger
5. View the memory issues

I've also generated memgraph's from Xcode from [TicTacToe](https://github.com/Steven0351/ComposableArchitectureMemGraphs/blob/master/TicTacToe%5B33689%5D.memgraph) as well as [my application](https://github.com/Steven0351/ComposableArchitectureMemGraphs/blob/master/ComposableArchitectureMemoryGraph.memgraph) that I'm building with ComposableArchitecture and put them in a GitHub repo so you could take a quick look if needed.

**Expected behavior**
No memory issues attributable to ComposableArchitecture

**Screenshots**
N/A

**Environment**
 - Xcode 11.5
 - Swift 5.2
 - macOS 10.15.5, iOS 13

**Additional context**
N/A

**Comment by mbrandonw** [comment] 2020-06-22 14:13
Hey @Steven0351, nice find!

Unfortunately, this seems to be a leak in Combine :( We were able to reproduce the link in a non-TCA application. It happens as soon as you concatenate two publishers where one of the publishers is a merge. For example, if you drop this in a brand new application you will reproduce the leak:

```swift
self.cancellable = Publishers.Concatenate(
  prefix: Empty<Int, Never>(completeImmediately: true),
  suffix: Publishers.MergeMany(Empty(completeImmediately: true))
)
  .print()
  .sink { _ in }
```

And this can happen easily in TCA because the `combine` operator on `Reducer` uses `MergeMany` under the hood and the `debug` operator uses `Concatenate`. Luckily this particular example (of using `combine` and `debug`) won't leak in release because the debug logic is hidden in a `#if DEBUG` flag, but any other time you use `Effect.concatenate` in a reducer you run the risk of leaking 😕

Hopefully this leak isn't too significant, and hopefully iOS 14 fixes this. I'm filing a feedback right now.

**Comment by mbrandonw** [comment] 2020-06-22 14:20
Just filed the following feedback: https://gist.github.com/mbrandonw/4959480547b5b07b8f381e5a0a1479c4

**Comment by mbrandonw** [comment] 2020-06-22 14:39
Also we've just opened #195 which should at least reducer some of the leak noise when building for `DEBUG` and using the `.debug()` reducer operator. It avoids using the `.concatenate` operator.

**Comment by Steven0351** [comment] 2020-06-22 16:53
Thanks for the quick feedback (and for pointfree!). That did indeed get rid of the vast majority of the leak noise for debug.

**Comment by mbrandonw** [comment] 2020-06-23 01:32
Great, I'll close this for now but feel free to re-open if you have more questions.

**Closed by mbrandonw** 2020-06-23 01:32 UTC
Labels: apple bug

**Comment by Steven0351** [comment] 2020-06-24 21:51
Just an FYI, I spoke to a Combine engineer regarding this issue and he thinks they have fixed this in the upcoming release.

**Comment by mbrandonw** [comment] 2020-06-24 22:52
Awesome! Thanks for doing that. We'll be sure to check it out in any future betas.
