### ISSUE TITLE
Build failure on Xcode 14.0 RC (14A309) when multiple (> 6) reducers are combined 

### ISSUE THREAD

**Issue by ylorn** [pointfreeco/swift-composable-architecture#1353] opened 2022-09-08 15:13 UTC
### Description

The following code used to compile in Xcode 13.4.1, but with Xcode 14, the compiler complains:

> The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

```swift
import ComposableArchitecture

struct SubState1: Equatable { }
enum SubAction1: Equatable { case dummyAction }
struct SubEnvironment1 { }
var subReducer1: Reducer<SubState1, SubAction1, SubEnvironment1> = .init { _, _, _ in return .none }

struct SubState2: Equatable { }
enum SubAction2: Equatable { case dummyAction }
struct SubEnvironment2 { }
var subReducer2: Reducer<SubState2, SubAction2, SubEnvironment2> = .init { _, _, _ in return .none }

struct SubState3: Equatable { }
enum SubAction3: Equatable { case dummyAction }
struct SubEnvironment3 { }
var subReducer3: Reducer<SubState3, SubAction3, SubEnvironment3> = .init { _, _, _ in return .none }

struct SubState4: Equatable { }
enum SubAction4: Equatable { case dummyAction }
struct SubEnvironment4 { }
var subReducer4: Reducer<SubState4, SubAction4, SubEnvironment4> = .init { _, _, _ in return .none }

struct SubState5: Equatable { }
enum SubAction5: Equatable { case dummyAction }
struct SubEnvironment5 { }
var subReducer5: Reducer<SubState5, SubAction5, SubEnvironment5> = .init { _, _, _ in return .none }

struct SubState6: Equatable { }
enum SubAction6: Equatable { case dummyAction }
struct SubEnvironment6 { }
var subReducer6: Reducer<SubState6, SubAction6, SubEnvironment6> = .init { _, _, _ in return .none }

struct MainState: Equatable {
    var subState1: SubState1 = .init()
    var subState2: SubState2 = .init()
    var subState3: SubState3 = .init()
    var subState4: SubState4 = .init()
    var subState5: SubState5 = .init()
    var subState6: SubState6 = .init()
}

enum MainAction: Equatable {
    case subState1(SubAction1)
    case subState2(SubAction2)
    case subState3(SubAction3)
    case subState4(SubAction4)
    case subState5(SubAction5)
    case subState6(SubAction6)
    case dummyAction
}

struct MainEnvironment {
    var subEnvironment1: SubEnvironment1 = .init()
    var subEnvironment2: SubEnvironment2 = .init()
    var subEnvironment3: SubEnvironment3 = .init()
    var subEnvironment4: SubEnvironment4 = .init()
    var subEnvironment5: SubEnvironment5 = .init()
    var subEnvironment6: SubEnvironment6 = .init()
}

var mainReducer: Reducer<MainState, MainAction, MainEnvironment> = .combine(
    subReducer1.pullback(
        state: \.subState1,
        action: /MainAction.subState1,
        environment: \.subEnvironment1
    ),

    subReducer2.pullback(
        state: \.subState2,
        action: /MainAction.subState2,
        environment: \.subEnvironment2
    ),

    subReducer3.pullback(
        state: \.subState3,
        action: /MainAction.subState3,
        environment: \.subEnvironment3
    ),

    subReducer4.pullback(
        state: \.subState4,
        action: /MainAction.subState4,
        environment: \.subEnvironment4
    ),

    subReducer5.pullback(
        state: \.subState5,
        action: /MainAction.subState5,
        environment: \.subEnvironment5
    ),

    subReducer6.pullback(
        state: \.subState6,
        action: /MainAction.subState6,
        environment: \.subEnvironment6
    ),

    .init { state, action, environment in
        switch action {
            case .subAction1:
                return .none

            case .subAction2:
                return .none

            case .subAction3:
                return .none

            case .subAction4:
                return .none

            case .subAction5:
                return .none

            case .subAction6:
                return .none

            case .dummyAction:
                return .none
        }
    }
)
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Actual behavior

<img width="1810" alt="Screen Shot 2022-09-08 at 11 02 47 AM" src="https://user-images.githubusercontent.com/1502810/189159784-2c71b5a3-7f38-48b7-be3f-5e51e14c0392.png">

### The Composable Architecture version information

0.39.1

### Destination operating system

iOS 16

### Xcode version information

14.0 (14A309)

### Swift Compiler version information

```shell
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by stephencelis** [comment] 2022-09-08 15:19
@ylorn We have noticed that using `.init` in Swift has seen some pretty serious performance regressions. See https://github.com/pointfreeco/xctest-dynamic-overlay/issues/30 for another example.

If you update your code sample above to avoid `.init` and be explicit with the types, you'll get a compiler error right away:

```swift
struct SubState1: Equatable { }
enum SubAction1: Equatable { case dummyAction }
struct SubEnvironment1 { }
var subReducer1 = Reducer<SubState1, SubAction1, SubEnvironment1> { _, _, _ in return .none }

struct SubState2: Equatable { }
enum SubAction2: Equatable { case dummyAction }
struct SubEnvironment2 { }
var subReducer2 = Reducer<SubState2, SubAction2, SubEnvironment2> { _, _, _ in return .none }

struct SubState3: Equatable { }
enum SubAction3: Equatable { case dummyAction }
struct SubEnvironment3 { }
var subReducer3 = Reducer<SubState3, SubAction3, SubEnvironment3> { _, _, _ in return .none }

struct SubState4: Equatable { }
enum SubAction4: Equatable { case dummyAction }
struct SubEnvironment4 { }
var subReducer4 = Reducer<SubState4, SubAction4, SubEnvironment4> { _, _, _ in return .none }

struct SubState5: Equatable { }
enum SubAction5: Equatable { case dummyAction }
struct SubEnvironment5 { }
var subReducer5 = Reducer<SubState5, SubAction5, SubEnvironment5> { _, _, _ in return .none }

struct SubState6: Equatable { }
enum SubAction6: Equatable { case dummyAction }
struct SubEnvironment6 { }
var subReducer6 = Reducer<SubState6, SubAction6, SubEnvironment6> { _, _, _ in return .none }

struct MainState: Equatable {
    var subState1 = SubState1()
    var subState2 = SubState2()
    var subState3 = SubState3()
    var subState4 = SubState4()
    var subState5 = SubState5()
    var subState6 = SubState6()
}

enum MainAction: Equatable {
    case subState1(SubAction1)
    case subState2(SubAction2)
    case subState3(SubAction3)
    case subState4(SubAction4)
    case subState5(SubAction5)
    case subState6(SubAction6)
    case dummyAction
}

struct MainEnvironment {
    var subEnvironment1 = SubEnvironment1()
    var subEnvironment2 = SubEnvironment2()
    var subEnvironment3 = SubEnvironment3()
    var subEnvironment4 = SubEnvironment4()
    var subEnvironment5 = SubEnvironment5()
    var subEnvironment6 = SubEnvironment6()
}

var mainReducer = Reducer<MainState, MainAction, MainEnvironment>.combine(
    subReducer1.pullback(
        state: \.subState1,
        action: /MainAction.subState1,
        environment: \.subEnvironment1
    ),

    subReducer2.pullback(
        state: \.subState2,
        action: /MainAction.subState2,
        environment: \.subEnvironment2
    ),

    subReducer3.pullback(
        state: \.subState3,
        action: /MainAction.subState3,
        environment: \.subEnvironment3
    ),

    subReducer4.pullback(
        state: \.subState4,
        action: /MainAction.subState4,
        environment: \.subEnvironment4
    ),

    subReducer5.pullback(
        state: \.subState5,
        action: /MainAction.subState5,
        environment: \.subEnvironment5
    ),

    subReducer6.pullback(
        state: \.subState6,
        action: /MainAction.subState6,
        environment: \.subEnvironment6
    ),

    Reducer<MainState, MainAction, MainEnvironment> { state, action, environment in
        switch action {
            case .subAction1: // 🛑 Type 'MainAction' has no member 'subAction1'
                return .none

            case .subAction2:
                return .none

            case .subAction3:
                return .none

            case .subAction4:
                return .none

            case .subAction5:
                return .none

            case .subAction6:
                return .none

            case .dummyAction:
                return .none
        }
    }
)
```

> 🛑 Type 'MainAction' has no member 'subAction1'

Because this isn't a bug with TCA I'm going to close this out, but please do file a bug on Swift to try to improve the compiler performance!

https://github.com/apple/swift/issues/new

**Closed by stephencelis** 2022-09-08 15:19 UTC
Labels: bug

**Comment by ylorn** [comment] 2022-09-08 20:32
Sorry for the fuss, I didn't realize I messed up the naming for the sub-actions.
