### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by imediayala** [pointfreeco/swift-composable-architecture#1459] opened 2022-10-10 12:33 UTC
### Description

Hi there,

I found really interesting your work and that there's definitely worth it give it a shot .

However i believe I found an issue, ViewStore.swift initialiser, objectWillChange.send() causes an undefined behaviour.
When Modifying any of the Object States changes are not published.

Sorry if in any case this is the expected behaviour on the demo project, the insides of the architecture are quite complex to my knowledge and I'm trying to get hang of it.

Keep up the great work !!

<img width="731" alt="Screenshot 2022-10-10 at 14 30 40" src="https://user-images.githubusercontent.com/7537081/194866792-568dc008-0172-4904-92e8-c15f0c47a044.png">

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

Publish state changes

### Actual behavior

Does not publish state changes 

### Steps to reproduce

- Clone repo https://github.com/pointfreeco/swift-composable-architecture.git
- Build SwiftUI CaseStudies 
- Modify an object in any of the cases, navigate back to list

### The Composable Architecture version information

built in swift-composable-architecture-main/Examples/CaseStudies

### Destination operating system

iOS 16.0

### Xcode version information

Xcode 14.0.1

**Comment by mbrandonw** [comment] 2022-10-10 13:05
Hi @imediayala, this is actually a bug in SwiftUI and is easily reproducible in vanilla SwiftUI. See #1319 for more information. Luckily it seems to be fixed in Xcode 14.1 beta.

I'm going to close this issue since it's already being discussed in #1319.

**Closed by mbrandonw** 2022-10-10 13:05 UTC
Labels: apple bug

**Comment by imediayala** [comment] 2022-10-11 07:43
Hey Brandon, thanks for letting me know.
