### ISSUE TITLE
Optional Reducer Crash In Three Column Navigation Layout

### ISSUE THREAD

**Issue by ghost** [pointfreeco/swift-composable-architecture#292] opened 2020-09-19 21:07 UTC
**Describe the bug**
When using default, three column layout for navigation,  push from detail view causes application crash.

**To Reproduce**
I used code from SwiftUI Case Studies to demonstrate behaviour. Just added navigation link to the Counter view.
It is only reproducible when navigation layout has three columns:
[NavDemo2.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5250594/NavDemo2.zip)

```swift
struct CounterState: Equatable {
  var count = 0
 var isNavigationActive = false
}

enum CounterAction: Equatable {
  case decrementButtonTapped
  case incrementButtonTapped
  case setNavigation(isActive: Bool)
}

struct CounterEnvironment {}

let counterReducer = Reducer<CounterState, CounterAction, CounterEnvironment> { state, action, _ in
  switch action {
  case .decrementButtonTapped:
    state.count -= 1
    return .none
  case .incrementButtonTapped:
    state.count += 1
    return .none
  case .setNavigation(isActive: true):
    state.isNavigationActive = true
    return .none
  case .setNavigation(isActive: false):
    state.isNavigationActive = false
    return .none
  }
}

struct CounterView: View {
  let store: Store<CounterState, CounterAction>

  var body: some View {
    WithViewStore(self.store) { viewStore in
    NavigationLink(
        destination: Text("Hello, World!"),
        isActive: viewStore.binding(get: {$0.isNavigationActive}, send: CounterAction.setNavigation(isActive:)),
        label: {
            EmptyView()
        })
        .buttonStyle(PlainButtonStyle())
      HStack {
        Button("−") { viewStore.send(.decrementButtonTapped) }
        Text("\(viewStore.count)")
          .font(Font.body.monospacedDigit())
        Button("+") { viewStore.send(.incrementButtonTapped) }
      }
      .toolbar {
        Button(action: {
            viewStore.send(.setNavigation(isActive: true))
        }, label: {
            Text("Push")
        })
      }
    }
  }
}
```

**Expected behavior**
Tap on "Push" should push new view, which happens, but after few moments app crashes. I tried to reproduce this in pure SwitUI, but could not. Still, it can be SwiftUI bug, but I wanted to report it in case that this is some strange case.

**Environment**
 - Xcode 12
 - Swift 5
 - iOS 14

**Comment by daniel-ezderm** [comment] 2020-09-24 03:34
I managed to reproduce exact behaviour in vanilla SwiftUI, and filed a feedback (FB8735501). However, in app that uses MVM along with SwiftUI this is not as destructive as when we are using composable-architecture. I'm not sure how to continue and what can be workaround this?
[NavigationCatch.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5273257/NavigationCatch.zip)

**Comment by stephencelis** [comment] 2020-10-30 15:44
@ghost We're tracking a similar issue here: https://github.com/pointfreeco/swift-composable-architecture/issues/282

If the discussion there (and the potential solution, here: https://github.com/pointfreeco/swift-composable-architecture/pull/296) seems to be the same, do you think we can close this as a duplicate?

Of note the crash you are encountering is a DEBUG-only crash meant to catch logic errors, though there are times in which you can safely ignore these actions, so we'd like to provide a workaround in the library soon.

**Comment by danielmoro** [comment] 2020-10-31 09:07
Yes, please, close it.

**Closed** 2021-07-07 19:26 UTC
