### ISSUE TITLE
The .legacyAlert modifier on a child view will be ignored. 

### ISSUE THREAD

**Issue by kdeda** [pointfreeco/swift-composable-architecture#2602] opened 2023-11-30 19:12 UTC
### Description

multiple calls to . legacyAlert are ignored

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

multiple calls to pop an alert when the state is non nil

### Actual behavior

the second call to .legacyAlert will never pop

### Steps to reproduce

Example code included with 2 Features as children of AppFeature

[LegacyAlert.zip](https://github.com/pointfreeco/swift-composable-architecture/files/13516816/LegacyAlert.zip)

### The Composable Architecture version information

0.59.0

### Destination operating system

macOS

### Xcode version information

14.2

**Comment by cdedagit** [comment] 2023-11-30 19:17
Issue persists on 
swift-composable-architecture.git @ 1.5.0 
swiftui-navigation.git @ 1.2.0

**Comment by mbrandonw** [comment] 2023-11-30 19:19
Hi @kdeda, can you please describe exactly what the problem is, and the steps to reproduce the problem. It is not clear right now.

Also, the project you have provided is quite complex. I would recommend trying to minimize it a great deal to make it easier for someone to help. Ideally it should be a project only involving `legacyAlert` since that is what you are reporting a problem with.

**Comment by kdeda** [comment] 2023-11-30 19:27
Say you have a main FeatureA with a ViewA that has 2 child features (FeatureB and FeatureC)
FeatureA can trigger and handle its own .legacyAlert

Each child feature, FeatureB and FeatureC has its own view, ViewA and ViewB
Each child feature can trigger and handle their own .legacyAlert

When these 2 child features are integrated into the main FeatureA/ViewA 
the management of .legacyAlert is interrupted.

The attached Xcode project should demonstrate the issue.

**Comment by cdedagit** [comment] 2023-11-30 19:31
> Also, the project you have provided is quite complex. I would recommend trying to minimize it a great deal to make it easier for someone to help. Ideally it should be a project only involving `legacyAlert` since that is what you are reporting a problem with.

I tried to make it as short as possible. 
One Parent Feature with 2 Child Features using Switch and CaseLet to switch between features.

**Comment by stephencelis** [comment] 2023-11-30 20:05
@kdeda I'm pretty certain is a vanilla SwiftUI problem with the original iOS 13 `alert` view modifier, which our library simply calls under the hood. One of the reasons why we have a "I have determined whether this bug is also reproducible in a vanilla SwiftUI project" requirement for issues is that a lot of these bugs are not TCA-specific, and it's good to confirm that vanilla behavior works first.

If I recall, the general workaround is to throw alerts into parts of the view hierarchy where they are better behaved, _e.g._ inside a `background` modifier, though you may want to search for vanilla solutions to the problem.

I'm going to close this for now, but if you do determine that the issue is reproducible only in TCA, please file a new issue that demonstrates it working in vanilla SwiftUI.

**Closed by stephencelis** 2023-11-30 20:05 UTC
Labels: apple bug

**Comment by kdeda** [comment] 2023-11-30 20:07
Thank you, 
I forgot about the entire vanilla thing, since I rarely use it.

**Comment by kdeda** [comment] 2023-11-30 20:13
Bingo moving around the location .legacyAlert is attached makes a difference.
So we have a workaround.

**Comment by mbrandonw** [comment] 2023-11-30 20:24
Oh sorry, I didn't see @stephencelis's response!
