### ISSUE TITLE
Reducer not being applied to changes for array's elements

### ISSUE THREAD

**Issue by marcocapano** [pointfreeco/swift-composable-architecture#134] opened 2020-05-26 12:00 UTC
Hello there! First of all, I've been using TCA and I must say it's an amazing piece or work👏🏻👏🏻👏🏻

I'm facing an issue, which I hope you can help me get clarity on:

in my App State, I've got an array of some model:
```swift
struct AppState: Equatable {
    var array: [Model] = []
}
```
I then have a list that displays the element in the array and creates a scoped store for each element:

```swift
ForEachStore(
    self.store.scope(
        state: \.array,
        action: { ListAction.rowActionAction($0.1) }
    ),
    content:  { scopedStore in
        NavigationLink(
            destination: self.row(store: scopedStore),
            label: { Row(store: scopedStore) }
        )
    }
)
```

The app reducer is then composed with a reduced that works on individual elements like this:

```swift
var appReducer = Reducer.combine(
    Reducer<AppState, AppAction, AppEnvironment> { state, action, environment in
        // .........some work here.....
    },
    elementReducer.forEach(
            state: \.array, //the app reducer is called but not this one????
            action: /AppAction.listAction(index:action:),
            environment: { _ in ElementEnvironment() }
    )
)
```

Now the actions are properly sent, but `elementReducer` is never called (the reducer it is composed with is though)

Any clue?
I believe it has to do with how I compose the reducers, since the views that display data from the scoped store display the correct data

Any help is appreciated!🙏

**Comment by stephencelis** [comment] 2020-05-26 13:24
Hey @marcocapano! Very strange that the reducer isn’t called. Can you reproduce the problem in a project that you can attach to this issue? It should give us the ability to debug things.

**Comment by marcocapano** [comment] 2020-05-26 13:56
I'll get an example project together today!
Very strange indeed, I don't exclude something might be wrong in how I'm doing things

**Comment by marcocapano** [comment] 2020-05-26 17:05
[ExampleProject.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4683773/ExampleProject.zip)

There you go @stephencelis ! Hopefully this is just something I'm doing wrong on my side🤞
To reproduce:

Launch the app
Tap on one of the cells to navigate to the detail
Tap + or - on the stepper, and observe the count doesn't change!

The code include comments about which reducers do get called and which do not get called.
You can find the comments at the end of SceneDelegate.swift, where the reducers are created

Thanks for looking into this!

**Comment by marcocapano** [comment] 2020-05-26 17:07
Using `.debug()` I got this printed when tapping on the - in the stepper for the third element in the collection (which by default has 8 as its `count`)

```
AppAction.listAction(
    ListAction.rowAction(
      index: 2,
      action: RowAction.detailAction(
        DetailAction.countChanged(
          7
        )
      )
    )
  )
  AppState(
    array: [
      Model(
        id: "91CC4145-491D-4359-B173-5723BD0013EE",
        count: 1
      ),
      Model(
        id: "1B86EC72-FEE9-464C-8665-19E6E702D303",
        count: 5
      ),
      Model(
        id: "8638BBCD-13AC-4010-B641-1284AB7B5BA1",
        count: 8
      ),
      Model(
        id: "F4D650C1-B3A5-4D9A-AB08-9B75C65ED570",
        count: 10
      ),
    ]
  )
```

So the action is received correctly (with the right value of `7`), but the third element in the collection did not change🤔

**Comment by mbrandonw** [comment] 2020-05-26 17:32
Hey @marcocapano , this is just a problem with domain modeling. Right now you have two sets of indexed actions, one in `ListAction` and one in `AppAction`. Currently you are sending `ListAction`s from the view but you are doing mutations from the indexed actions in `AppAction`, so one just isn't influencing the other.

I'm not sure if you really do need to sets of indexed actions, but the current code can be fixed by consolidating this into a single set of indexed actions: [ExampleProject-fixed.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4683943/ExampleProject-fixed.zip)

Indexed actions can be tricky and kind of mind trippy, but the idea is that the parent domain (the one that represents the list of items) holds a case of indexed actions of the child domain (the one that represents a single row in a list). The Todos example app in the repo and our most recent tour episodes go into more detail so you may find that interesting.

Since it doesn't seem like this is a TCA-specific bug would you be ok with closing this? And if you want to discuss further you could open a topic on the [Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture/61).

**Comment by marcocapano** [comment] 2020-05-26 20:20
Totally ok with closing! Thanks for clarifying! I’ll have a look at the project sent asap 🙏🏻 you guys rock!

**Comment by mbrandonw** [comment] 2020-05-26 23:07
Cool, will close for now, but feel free to re-open if you think it's a TCA bug, or post on Swift forums if you want to discuss more.

**Closed by mbrandonw** 2020-05-26 23:07 UTC
