### ISSUE TITLE
iOS 16 packages have dependency conflict warning when importing Composable

### ISSUE THREAD

**Issue by krze** [pointfreeco/swift-composable-architecture#3255] opened 2024-07-24 16:51 UTC
### Description

When you have a project with a package added to it which supports iOS/tvOS 16, then add Swift Composable Architecture as a dependency, the resolve dependencies step will display a warning about conflicting dependencies regarding `swift-syntax` between the `swift-composable-architecture` package and its dependencies. This is because the Swift 5.9 package version of Composable uses the `swift-syntax` package from `"https://github.com/apple/swift-syntax"` instead of `"https://github.com/swiftlang/swift-syntax"` like its dependencies.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

No warnings appear

### Actual behavior

Several warnings appear when resolving package dependencies:

```
➜  Test-Package-App git:(main) ✗ xcodebuild -resolvePackageDependencies
Command line invocation:
    /Applications/Xcode-15.3.0.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph

Updating from https://github.com/pointfreeco/swiftui-navigation

Updating from https://github.com/pointfreeco/swift-composable-architecture.git

Updating from https://github.com/pointfreeco/swift-identified-collections

Updating from https://github.com/pointfreeco/xctest-dynamic-overlay

Updating from https://github.com/pointfreeco/swift-clocks

Updating from https://github.com/pointfreeco/combine-schedulers

Updating from https://github.com/pointfreeco/swift-issue-reporting

Updating from https://github.com/apple/swift-collections

Updating from https://github.com/pointfreeco/swift-case-paths

Updating from https://github.com/pointfreeco/swift-dependencies

Updating from https://github.com/pointfreeco/swift-perception

Updating from https://github.com/pointfreeco/swift-custom-dump

Updating from https://github.com/apple/swift-syntax

Updating from https://github.com/pointfreeco/swift-concurrency-extras

'swift-case-paths' dependency on 'https://github.com/swiftlang/swift-syntax' conflicts with dependency on 'https://github.com/apple/swift-syntax' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.

'swift-dependencies' dependency on 'https://github.com/swiftlang/swift-syntax' conflicts with dependency on 'https://github.com/apple/swift-syntax' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.

'swift-perception' dependency on 'https://github.com/swiftlang/swift-syntax' conflicts with dependency on 'https://github.com/apple/swift-syntax' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.

multiple similar targets 'IssueReporting', 'IssueReportingTestSupport', 'XCTestDynamicOverlay' appear in package 'swift-issue-reporting' and 'xctest-dynamic-overlay', this may indicate that the two packages are the same and can be de-duplicated by using mirrors. if they are not duplicate consider using the `moduleAliases` parameter in manifest to provide unique names

Resolved source packages:
  swift-identified-collections: https://github.com/pointfreeco/swift-identified-collections @ 1.1.0
  xctest-dynamic-overlay: https://github.com/pointfreeco/xctest-dynamic-overlay @ 1.2.2
  xctest-dynamic-overlay: https://github.com/pointfreeco/swift-issue-reporting @ 1.2.2
  swift-perception: https://github.com/pointfreeco/swift-perception @ 1.3.3
  TestImportPackage: /Users/kenneth.krzeminski/dev/TestImportPackage
  swift-concurrency-extras: https://github.com/pointfreeco/swift-concurrency-extras @ 1.1.0
  combine-schedulers: https://github.com/pointfreeco/combine-schedulers @ 1.0.1
  swift-composable-architecture: https://github.com/pointfreeco/swift-composable-architecture.git @ 1.11.2
  swift-syntax: https://github.com/apple/swift-syntax @ 600.0.0-prerelease-2024-06-12
  swift-custom-dump: https://github.com/pointfreeco/swift-custom-dump @ 1.3.1
  swift-dependencies: https://github.com/pointfreeco/swift-dependencies @ 1.3.4
  swift-case-paths: https://github.com/pointfreeco/swift-case-paths @ 1.5.3
  swift-clocks: https://github.com/pointfreeco/swift-clocks @ 1.0.3
  swiftui-navigation: https://github.com/pointfreeco/swiftui-navigation @ 1.5.2
  swift-collections: https://github.com/apple/swift-collections @ 1.1.2

2024-07-24 12:38:04.047 xcodebuild[14219:2732218] Writing error result bundle to /var/folders/tr/1ww2xbr96s7998h4wpq3d1t00000gp/T/ResultBundle_2024-24-07_12-38-0004.xcresult
xcodebuild: error: Could not resolve package dependencies:
  multiple similar targets 'IssueReporting', 'IssueReportingTestSupport', 'XCTestDynamicOverlay' appear in package 'swift-issue-reporting' and 'xctest-dynamic-overlay', this may indicate that the two packages are the same and can be de-duplicated by using mirrors. if they are not duplicate consider using the `moduleAliases` parameter in manifest to provide unique names
```

### Steps to reproduce

1. Create a new xcode project
2. Create a package within the project, then add it to the project
3. Add `swift-composable-architecture` as a dependency to the package and ensure at least one target in the package depends on it (I used 1.11.2)
4. Compile the app, or run `xcodebuild -resolvePackageDependencies` from the project directory
5. Observe warnings

### The Composable Architecture version information

1.11.2

### Destination operating system

iOS 16

### Xcode version information

15.3

### Swift Compiler version information

```shell
➜  Test-Package-App git:(main) ✗ xcrun swiftc --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

Sample app:
[Sample.zip](https://github.com/user-attachments/files/16365269/Sample.zip)

**Comment by funkyboy** [comment] 2024-07-24 16:58
I have the same error using different versions:

Xcode 15.0.1
Destination operating system: iOS 17
Composable Architecture: 1.4.2

Maybe this is due to the renaming of the XCTestDynamicOverlay repo?

**Comment by stephencelis** [comment] 2024-07-24 20:01
Thanks for the example! We were able to reproduce and determine that SwiftPM does not resolve the dependency rename in Xcode while it does work in other contexts. We believe this should be fixed with a pinned TCA as long as you update any other previously conflicting dependency to its latest version.

**Comment by funkyboy** [comment] 2024-07-25 08:12
I had to run `xcodebuild -resolvePackageDependencies` to fix it. 
Selecting "Update to Latest Package Versions" in Xcode didn't work 🤷.

There's still some warnings but at least I can now compile and go on.

<img width="1230" alt="Screenshot 2024-07-25 at 10 06 47" src="https://github.com/user-attachments/assets/2c996512-8adf-4b6a-90a8-fb26f924c264">

Thanks for the quick fix!

**Comment by krze** [comment] 2024-07-25 18:26
Hi @stephencelis, I pinned TCA in `Package.resolved` and it did not resolve the warnings. I've attached the changes to the example app to demonstrate the issue. Note the added `Package.resolved` in the package with the pin.
[Sample 2.zip](https://github.com/user-attachments/files/16382309/Sample.2.zip)

**Comment by mbrandonw** [comment] 2024-07-25 18:36
Hi @krze, if you update the packages to their latest version (TCA can stay at 1.11.2) it should work:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/7d4fe0c5-3beb-4233-9714-626ca99eaa53">

**Comment by mbrandonw** [comment] 2024-07-25 18:38
I think this issue has now been fixed so I am going to close this out. Please feel free to open a discussion if you have more questions!

**Closed by mbrandonw** 2024-07-25 18:38 UTC
Labels: bug

**Comment by krze** [comment] 2024-07-26 15:24
Confirmed, this is fixed.
