### ISSUE TITLE
Several independent ViewStores in a single View.

### ISSUE THREAD

**Issue by koralle** [pointfreeco/swift-composable-architecture#356] opened 2021-01-20 12:12 UTC
**Question**
I' m note sure which my idea is correct or not.
I was faced with a situation where I wanted to reference **several independent `viewStore`s within a single View**.

So, I came up with the following code implementation.
However, is that idea a correct implementation according to the TCA philosophy?
Should I review the design of Store and State?

Environment:
* XCode version 12.3 (12C33)
* Swift version 5.3.2
* iOS version 14.2
* swift-composable-architecture version 0.10.0

```swift
struct RootState: Equatable {
    xxxxx: XXXXXState(),
    yyyyy: YYYYYState(),
}

enum RootAction: Equtable {
    case xxxxx(XXXXXAction)
    case yyyyy(YYYYYAction)
}

struct RootEnvironment {}

let rootReducer = Reducer<RootState, RootAction, RootAppEnvironment>.combine(
    ...
)

struct ContentView: View {

    // Store
    private let store: Store<RootState, RootAction>
    
    // ViewStore
    @ObservedObject private var xxxxxViewStore: ViewStore<XXXXXState, XXXXXAction>
    @ObservedObject private var yyyyyViewStore: ViewStore<YYYYYState, YYYYYAction>

    init (store: Store<RootState, RootAction>) {
        
        self.store = store

        self.xxxxxViewStore = ViewStore(
            store.scope(
                state: { $0.xxxxx },
                action: RootAction.xxxxx
            )
        )
        self.yyyyyViewStore = ViewStore(
            store.scope(
                state: { $0.yyyyy },
                action: RootAction.yyyyy
            )
        )
    }

    var body: some View {
        ...
    }
}

```

**Comment by stephencelis** [comment] 2021-01-20 14:44
Hi @koralle! If this is a question and not a bug report, would you be okay with moving it to the discussions section of the repo? As for the question, it's totally fine to have multiple view stores in a single view, but in general it is much more typical for a view to have a single view store that has been scoped to just what that view needs to do its job. In this case, assuming `xxxxx` and `yyyyy` are a subset of the `Root` domain (and not it in its entirety) you could also create a "view" domain by doing the following:

```swift
struct ContentView: View {
  struct ViewState {
    let xxxxx: XXXXXState
    let yyyyy: YYYYYState
  }
  enum ViewAction {
    case xxxxx: XXXXXAction
    case yyyyy: YYYYYAction
  }
  // ... init() {
  ViewStore(
    store.scope(
      state: { ViewState(xxxxx: $0.xxxxx, yyyyy: $0.yyyyy) }
      action: {
        switch $0 {
        case let .xxxxx(action): return .xxxxx(action)
        case let .yyyyy(action): return .yyyyy(action)
      }
    )
  )
  // ...
}
```

**Comment by koralle** [comment] 2021-01-21 00:48
@stephencelis 

> If this is a question and not a bug report, would you be okay with moving it to the discussions section of the repo?

That is OK.

> As for the question, it's totally fine to have multiple view stores in a single view, but in general it is much more typical for a view to have a single view store that has been scoped to just what that view needs to do its job. In this case, assuming xxxxx and yyyyy are a subset of the Root domain (and not it in its entirety) you could also create a "view" domain by doing the following:

Thanks for the quick answer! I will follow your advice.

**Closed** 2021-01-21 00:48 UTC
