### ISSUE TITLE
Crash after remove

### ISSUE THREAD

**Issue by buscarini** [pointfreeco/swift-composable-architecture#152] opened 2020-05-29 14:43 UTC
I'm not sure if this is a bug or if I'm doing something wrong. I'm trying to make a small macos app, which has a navigation view inside another navigation view, so it would be a 3 panes app, a groups list, an items list and a detail view. If I try to remove a group or an item the app crashes. I started with simple arrays and int indexes, but I switched to an IdentifiedArrayOf, but nothing works:

`
Fatal error: Can't update element with identifier B699DB06-EFA9-4957-B0E9-DAAE764EE938 with nil.

If you are trying to remove an element from the array, use the "remove(id:) method.":`

Rest assured, I am using the remove(id:) method.

I'm also removing the selection when I remove an item if it's the selected one, but that doesn't update the detail panel.

**Comment by pcolton** [comment] 2020-05-29 15:18
You may want to take a look at this solution, your's might be similar issue: https://forums.swift.org/t/complex-use-case-for-shared-state-and-null-exception/36942

**Comment by stephencelis** [comment] 2020-05-29 15:59
@buscarini Can you ensure that an element with that UUID still in the array? We could probably tweak the messaging of that error in `remove(id:)`, or make `remove(id:)` "safe" (we kept it unsafe to be inline with `remove(at:)` in the Standard Library).

Also, if an element with that UUID _is_ still in the array, can you please fill out our issue template? It's difficult to debug without a repro:

    **Describe the bug**
    Give a clear and concise description of what the bug is.

    **To Reproduce**
    Zip up a project that reproduces the behavior and attach it by dragging it here.

    ```swift
    // And/or enter code that reproduces the behavior here.

    ```

    **Expected behavior**
    Give a clear and concise description of what you expected to happen.

    **Screenshots**
    If applicable, add screenshots to help explain your problem.

    **Environment**
     - Xcode [e.g. 11.4.1]
     - Swift [e.g. 5.2.2]
     - OS (if applicable): [e.g. iOS 13]

    **Additional context**
    Add any more context about the problem here.

**Comment by buscarini** [comment] 2020-05-29 17:19
I'll try to extract a simple example to reproduce this, but in the meantime here's more info:

1. There isn't an element with that UUID in the array, the id mentioned is the item that was just removed, so it makes sense that it's not in the array.
2. It has something to do with the navigation links, if I directly embed the detail view in the list there's no crash.

**Comment by buscarini** [comment] 2020-05-29 17:33
I found it!
The problem is I was using 
`NavigationLink init(destination: Destination, isActive: Binding<Bool>, @ViewBuilder label: () -> Label)`

If I switch to using `init<V>(destination: Destination, tag: V, selection: Binding<V?>, @ViewBuilder label: () -> Label)` then I don't see the crash.

In any way the behavior is weird, if I have 2 items A and B, and I select B and then remove it, I still see the details of the removed object B, until I select A. I'm not sure if there's anything to be done here, though, maybe it's just a SwiftUI issue. Maybe it would be useful to warn about this function in the printed error? Let's hope Apple fixes a lot of this stuff in the next releases.

**Comment by stephencelis** [comment] 2020-05-29 18:55
Dang that's frustrating. If you can still find the time to share the repro that would help us better understand how we can best update the assert failure message. It'd also be good to file as feedback with Apple if it _is_ a SwiftUI bug that can be reproduced outside a TCA project

**Comment by grinder81** [comment] 2020-05-29 18:58
Your issue must be related with mine in [here](https://forums.swift.org/t/complex-use-case-for-shared-state-and-null-exception/36942) 

The core of the problem is: if you have a list of items and somehow id is changing while you are adding and removing then it will happen. I shared my repo and it might help you @buscarini

**Comment by buscarini** [comment] 2020-05-30 07:46
I made a simple example where this can be seen:

https://github.com/buscarini/NavigationLinkCrash

@grinder81 Unless I overlooked something I don't think your issue is related, I'm not creating new uuids or changing them while removing items.

**Comment by jeffersonsetiawan** [comment] 2020-06-03 08:35
I have similar problem with this simple list that can be deleted

**Describe the bug**
It's like Todo app, but every Todo have button to delete itself. the delete action is in the cell, but the removing process is on the parent.
```
AppState -> RemovableState
AppAction -> RemovableAction
```

**To Reproduce**
Open xcode, compile, press add, and then remove.

```swift
struct AppState: Equatable {
    var data: IdentifiedArrayOf<RemovableState> = []
}

enum AppAction: Equatable {
    case removable(id: String, action: RemovableAction)
    case add
}

let appReducer = Reducer<AppState, AppAction, Void> { state, action, _ in
    switch action {
    case .removable(let uuid, let action) where action == .remove:
        state.data.remove(id: uuid)
        return .none
    case .add:
        state.data.append(RemovableState(id: UUID().uuidString))
        return .none
    default:
        return .none
    }
}.combined(with:
    removableReducer.forEach(
        state: \.data,
        action: /AppAction.removable(id:action:),
        environment: { _ in }
    )
)

struct ContentView: View {
    let store: Store<AppState, AppAction>
    var body: some View {
        WithViewStore(self.store) { viewStore in
            ScrollView(.vertical, showsIndicators: true) {
                VStack {
                    Text("Title")
                    ForEachStore(
                        self.store.scope(state: \.data, action: AppAction.removable),
                        content: RemovableView.init(store:)
                    )
                    Spacer()
                    Button("+ Add") { viewStore.send(.add) }
                }
                .padding()
                .frame(maxWidth: .infinity)
            }
        }
    }
}


struct RemovableState: Equatable, Identifiable {
    var id: String
    var price: String = "0"
}
enum RemovableAction: Equatable {
    case remove
    case priceChanged(String)
}

let removableReducer = Reducer<RemovableState, RemovableAction, Void> { state, action, _ in
    switch action {
    case .remove: return .none
    case .priceChanged(let price):
        state.price = price
        return .none
    }
}

struct RemovableView: View {
    let store: Store<RemovableState, RemovableAction>
    var body: some View {
        WithViewStore(self.store) { viewStore in
            HStack {
                TextField("Price", text: viewStore.binding(
                    get: \.price,
                    send: RemovableAction.priceChanged
                ))
                Button("Remove") { viewStore.send(.remove) }
            }.border(Color.gray)
            
        }
    }
}

```

**Expected behavior**
Item removed and not crash

**Environment**
 - Xcode 11.5
 - Swift 5.2.2
 - OS (if applicable): iOS 13.5

**Additional context**
here is the repo: https://github.com/jeffersonsetiawan/SubscriptFatalError

**Comment by pcolton** [comment] 2020-06-03 13:39
@jeffersonsetiawan Your `removableReducer.forEach` reducer is running *after* you have already deleted the item. Put that ahead of your other reducer and it all works fine.

```swift
let appReducer: Reducer<AppState, AppAction, Void> = .combine(
    
    removableReducer.forEach(
           state: \.data,
           action: /AppAction.removable(id:action:),
           environment: { _ in }
       )
        
    ,
    
    .init { state, action, _ in
        switch action {
            case .removable(let uuid, let action) where action == .remove:
                state.data.remove(id: uuid)
                return .none
            case .add:
                state.data.append(RemovableState(id: UUID().uuidString))
                return .none
            default:
                return .none
        }
    }
)
```

**Comment by stephencelis** [comment] 2020-06-03 13:51
Thanks for helping out, @pcolton!

@jeffersonsetiawan We're planning to merge #154 soon to help provide better error messaging for this in the future.

**Comment by jeffersonsetiawan** [comment] 2020-06-03 15:43
woahhh, thank you very much @pcolton ! just realize the order is matter.

Thanks @stephencelis , superb awesome library and the series 👍

**Comment by stephencelis** [comment] 2020-06-15 18:05
@buscarini Think it's OK to close this now that you have a solution and we've updated the error messaging?

**Closed** 2020-06-16 10:33 UTC
Labels: question
