### ISSUE TITLE
module 'ComposableArchitecture' was not compiled for testing

### ISSUE THREAD

**Issue by eimantas** [pointfreeco/swift-composable-architecture#22] opened 2020-05-06 04:36 UTC
I added TCA to my application (without adding TCA test support). I can't seem to get the SwiftUI previews working anymore. After pressing "Resume" on the canvas I get the "Build Failed" HUD. Tapping "Diagnostics" gives me this error:

```log
SchemeBuildError: Failed to build the scheme "App"

Build target ComposableArchitectureTestSupport:
note: Set ENABLE_PREVIEWS=NO because SWIFT_OPTIMIZATION_LEVEL=-Owholemodule, expected -Onone (in target 'ComposableArchitectureTestSupport' from project 'swift-composable-architecture')


Compile Swift source files:
/Users/eimantas/Development/DerivedData/App-cvsbxwitwserczdehyykapbndqjo/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitectureTestSupport/TestStore.swift:4:18: error: module 'ComposableArchitecture' was not compiled for testing
@testable import ComposableArchitecture
```

I understand this is not the problem with TCA itself, but with either Xcode or my project settings. 

I turned off `-Owholemodule` optimisation in ALL of the targets (the app has a watch app counterpart). I also turned off `ENABLE_PREVIEWS`. Even with that setting it tells me to turn them off. The project builds and I can run tests, but when it comes to getting the previews - for some reason I can't get it to build.

It's also strange that tests run just fine (because they don't have dependency on TCA's Test Support library) and the app builds. But previews for some reason just don't show up.

I also just checked the settings with vanilla project that contains TCA and it's test support - the build settings are _identical_ which makes me even more confused :(

**Comment by stephencelis** [comment] 2020-05-06 14:35
Let's see if anyone else encounters this issue. At the moment we need a way to reproduce to troubleshoot it. Could very well be a gotcha with tooling and maybe we could document the issue and workaround when we know it!

**Comment by alexito4** [comment] 2020-05-06 18:50
I just added the library to a new iOS project and previews don't compile anymore. The only error Xcode points to is the Reducer file.

<img width="1415" alt="Screenshot 2020-05-06 at 20 48 07" src="https://user-images.githubusercontent.com/750912/81216238-e6708e00-8fda-11ea-8bd6-e1a635778113.png">

But I don't think this is the issue, it seems like the compiler is trapping somewhere. I see "Command CompileSwift failed with a nonzero exit code" for a lot of files in the library.

<img width="1045" alt="Screenshot 2020-05-06 at 20 49 31" src="https://user-images.githubusercontent.com/750912/81216396-20419480-8fdb-11ea-89d7-d0a2e6487589.png">

The funny thing is compiling and running works just fine, is just when Xcode compiles for previews. ¯\_(ツ)_/¯

**Comment by stephencelis** [comment] 2020-05-06 18:59
@alexito4 Can you zip the project up an attach it here? Would love to pull it down and troubleshoot.

**Comment by mrkd** [comment] 2020-05-07 02:26
[Todos.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4590359/Todos.zip)

**Comment by huynguyen** [comment] 2020-05-07 02:39
I've narrowed this down a little and it's somehow related to https://github.com/pointfreeco/swift-composable-architecture/commit/4016008d87db1e6c9b1533a8f74e607758bcaacf#diff-cff665441bd6f271c87862ed5497c3b3R101-R103

It seems that doing anything related to `self` after the `yield` causes the crash:
https://gist.github.com/huynguyen/f4e3622531b35d2da68b2b0ade20706d#file-gistfile1-txt-L68-L91

I'm not familiar with the behavior of `_modify` and `yield` but commenting out the offending lines enables previews again. Additionally using `self` after `yield` [on the func above ](https://github.com/pointfreeco/swift-composable-architecture/blob/be42d850ef3a8e9120dc82e874672718cb473607/Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift#L91) will cause the same kind of error.

I can also upload another example if it helps, but it's just a blank project with the TCA added via swiftPM, not even imported.

**Comment by huynguyen** [comment] 2020-05-07 02:58
Maybe the way forward is to go back to the blessed `set` property observer and take the performance hit for this case?

```swift
  public subscript(id id: ID) -> Element? {
    get {
      self.dictionary[id]
    }
    set {
      self.dictionary[id] = newValue
      if self.dictionary[id] == nil {
        self.ids.removeAll(where: { $0 == id })
      }
    }
  }
```

**Comment by klaaspieter** [comment] 2020-05-07 06:06
Adding another data point. It started failing for me after I upgraded to 0.1.1. Downgrading to 0.1.0 solves the issue and makes previews build again.

This is in Xcode 11.4.0.

**Comment by buscarini** [comment] 2020-05-07 07:15
Same thing here. I had the same issue, and downgrading to 0.1.0 fixed it.

**Comment by alexito4** [comment] 2020-05-07 08:00
> @alexito4 Can you zip the project up and attach it here? Would love to pull it down and troubleshoot.

I just sent you a DM with the zip.

**Comment by stephencelis** [comment] 2020-05-07 13:11
> It seems that doing anything related to `self` after the `yield` causes the crash:
> https://gist.github.com/huynguyen/f4e3622531b35d2da68b2b0ade20706d#file-gistfile1-txt-L68-L91

Good find!

> Maybe the way forward is to go back to the blessed `set` property observer and take the performance hit for this case?

😔 I think so. It shouldn't be too much of a performance hit, and we can evaluate other routes of optimizing `IdentifiedArray` in the future.

I'll prepare a fix and a quick 0.1.2 bump, thanks!

**Comment by stephencelis** [comment] 2020-05-07 13:25
@eimantas (and everyone experiencing similar issues): could you point your projects towards this branch/commit and confirm that it fixes things? https://github.com/pointfreeco/swift-composable-architecture/pull/31

**Comment by eimantas** [comment] 2020-05-07 13:40
I appreciate the effort!

I've pointed the SPM to the branch, however it doesn't fix my issue. I still get the same broken build when trying to preview the views.

I wonder if I'm writing some funky UI view 🤔

**Comment by alexito4** [comment] 2020-05-07 14:42
> could you point your projects towards this branch/commit and confirm that it fixes things? #31

Pointing to master and seems to be working 👌 

> I've pointed the SPM to the branch, however it doesn't fix my issue. I still get the same broken build when trying to preview the views.

not useful answer I know, but make sure you clean everything and close Xcode. Xcode & previews are quite stubborn 😂

**Comment by stephencelis** [comment] 2020-05-07 15:01
> I've pointed the SPM to the branch, however it doesn't fix my issue. I still get the same broken build when trying to preview the views.

Bummer. Let us know if you find a fix or a repro you can attach! At least the PR fixed things for everyone else 😅 I've released 0.1.2, which folks can bump to.

**Comment by eimantas** [comment] 2020-05-07 15:06
Thanks, as long as I'm able at least to run the app with CTA I'll keep updating and trying :)

**Comment by eimantas** [comment] 2020-05-11 07:24
So I went the easy path with lots of work - setup an empty project and moved all the files to it as well as readded all the Swift packages and updated all the custom project settings.

It now builds, runs tests and I can see the previews.

**Comment by stephencelis** [comment] 2020-05-11 13:42
Glad to hear migrating things over worked. I'm sure it was a pain! We'll close this out but will try to be mindful of any similar issues that come in in the future. Would be nice to know what exactly about these Xcode projects is the problem.

**Closed by stephencelis** 2020-05-11 13:42 UTC
Labels: question

**Comment by eimantas** [comment] 2020-05-13 18:34
So I found the answer to the issue. I found it in [this thread](https://forums.developer.apple.com/thread/119327) from Apple's Developer forums.

Long story short - Xcode can only build `Debug` configuration of Swift packages. So be sure that the thing you're building is actually using Debug scheme and not some other (like I after renaming `Debug` to `Develop`) 🤦

**Comment by mbrandonw** [comment] 2020-05-13 18:41
Oh nice, good find! Thanks for following up

**Comment by dfalmeida** [comment] 2020-11-27 11:07
> So I found the answer to the issue. I found it in [this thread](https://forums.developer.apple.com/thread/119327) from Apple's Developer forums.
> 
> Long story short - Xcode can only build `Debug` configuration of Swift packages. So be sure that the thing you're building is actually using Debug scheme and not some other (like I after renaming `Debug` to `Develop`) 🤦

Faced a similar problem a few hours ago with the error ´Cannot find 'TestStore' in scope´. Note that the `TestStore` is preceded with a `#if DEBUG`. At that time I assumed something went wrong with the debug flags on project settings. NOT! 🤦 
Later I found out that what worked for me is to have the configuration names with a `Debug` prefix, like: 'Debug-Staging' Hope this helps someone else! 🙏
