### ISSUE TITLE
If Let UIKit issue in 0.20.0

### ISSUE THREAD

**Issue by DavidKmn** [pointfreeco/swift-composable-architecture#621] opened 2021-06-28 20:49 UTC
**If Let Store no longer executed the else condition after the scoped state is set to nil**

We have not changed any code and just migrated to 0.20.0 from 0.18.0, now we no longer get the dismissal else case executing after we set the scoped state to a value of nil

**Comment by stephencelis** [comment] 2021-06-28 21:31
@DavidKmn Thanks for the report!

First, can you try both 0.19.0 and 0.20.0 to better determine which release introduced the problem?

After that, can you also please attach a sample project that reproduces the issue? The repo comes with a TicTacToe demo application with a full UIKit implementation that uses `Store.ifLet` for navigation, and everything appears to be working as expected in 0.20.0.

**Comment by stephencelis** [comment] 2021-06-28 21:34
We also have a test case that exercises the `else` branch here:

https://github.com/pointfreeco/swift-composable-architecture/blob/3ca8249bd3262e9837c6cb4d352cc58e370e33fc/Tests/ComposableArchitectureTests/StoreTests.swift#L284-L332

If you have any ideas from your project that could make this test case fail, that also may help us get to the root of the issue.

**Comment by DavidKmn** [comment] 2021-06-29 05:23
Thanks for the response. 

After investigating further I have found the following.
First of the issue is not to do with the else condition in the ifLet function. 
Second of all this happened between versions 0.19.0 and 0.20.0.

We have a screen that gets presented using the ifLet operator via .present when some child state is set. Then within this presented screen there is a button that upon tap does 2 things:
1) it sets a property called dismissView = true. This is then used in the ViewStore and passed down to the VC that after getting true on this property calls .dismiss on self. 
2) it sends out a .delegate(.endActivity) effect that is then caught in the parent reducer. The parent reducer then sets the state of this presented view to nil.

I see some changes have been made to the calls made to the view store, and what seems to have happened is that condition 1 from above is no longer true. Meaning that the dismissView no longer gets set leading to the vc to not dismissing itself. 
@stephencelis

**Comment by stephencelis** [comment] 2021-06-29 11:41
@DavidKmn Without a sample project I'm going to have to make a few assumptions here 😅 If I've made any wrong assumptions, a sample project would really be helpful to troubleshoot.

Assuming `.delegate(.endActivity)` is synchronous, you may be seeing a consequence of the following change from [0.20.0](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.20.0):

> - Performance improvement/fix: a store publisher will only emit a single state change per synchronous Store.send and asynchronous effect received. This means synchronous effects (returned immediately from a reducer via Effect.init(value:)) will no longer result in extra publisher emissions.

Prior to 0.20.0, TCA state changes were always witnessed/rendered "once" per `send` in SwiftUI, but observers of the store publisher received every intermediate mutation from every synchronous effect. We've squashed things down so that 1 send = 1 state emission for a few reasons:

- It makes things more consistent. Both SwiftUI and manual observation receive the same number of updates
- It avoids rendering hitches in UIKit/etc. apps. Previously, if you mutated state in your reducer but overrode that state in a synchronous effect, both states would emit to the view, which could result in glitchy rendering.
- It improves performance more generally. While we don't recommend queueing up 100s of synchronous effects all at once, it is possible to do, and rather than bog a UIKit app down with 100s of emissions, we think it makes more sense to emit a single time once things are complete.

In your case, it sounds like you had a view that depended on observing `dismissView = true`, but now the system has already `nil`d out that state before it can be observed.

There are 2 ways to fix this:

- Add a `.receive(on:)` to your synchronous effect so that it is observed on the next "tick"
- Remodel things a bit so that, e.g., view dismissal observes the state going `nil` rather than a child field `dismissView` going `true`.

**Comment by DavidKmn** [comment] 2021-06-30 05:46
Thanks for the response. You are correct in your assumptions. The .delegate(.endActivity) is returned as a synchronous effect via a .init(value:) call. So reading your explanation I kind of understand the issue. The state gets set to nil after this effect and the dismissView gets set right before. Are you implying that in the new release these essential happen in 1 tick meaning there is essentially nothing to receive in the view store afterwards? 

The first solution seems a bit hacky although a quick fix. I'm not sure I understand what your second solution is. Let's say we have a parent VC and a child VC, currently the observation for dismissView is in the child vc, and as soon it's set to true we call dismiss on self. How would we setup an observation for the state going to nil in the child vc? (Are you prosoping to use something like the ifLet operator and it's else statement?) Or am I misunderstanding your solution.

**Comment by stephencelis** [comment] 2021-06-30 13:50
> Are you implying that in the new release these essential happen in 1 tick meaning there is essentially nothing to receive in the view store afterwards?

Yep, exactly, for the reasons given we made this change. We understand it's breaking, but the `.receive(on:)` solution is a quick fix for those affected.

> The first solution seems a bit hacky although a quick fix. I'm not sure I understand what your second solution is. Let's say we have a parent VC and a child VC, currently the observation for dismissView is in the child vc, and as soon it's set to true we call dismiss on self. How would we setup an observation for the state going to nil in the child vc? (Are you prosoping to use something like the ifLet operator and it's else statement?) Or am I misunderstanding your solution.

It sounds like `ifLet` is already driving navigation based on optional state, but you want the child to handle dismissal. We've found that it makes the most sense for the parent to manage the presentation of a child. The child may still "dismiss" itself, either by using built-in affordances, like the navigation bar back button or UIKit/SwiftUI methods, or by sending an action that the parent domain listens to, like your delegate action, and then the parent can do its work to `nil` out that state. Without code it's hard to give more guidance than this, but hopefully it helps!

**Comment by stephencelis** [comment] 2021-07-07 19:11
@DavidKmn Since this change is intentional and covered in the release log, I'm going to close the issue. If you would like to discuss the change more, please feel free to open a GitHub discussion!

**Closed by stephencelis** 2021-07-07 19:11 UTC
