### ISSUE TITLE
IdentifiedArrayOf<ConversationOutPut> not update from parents state 

### ISSUE THREAD

**Issue by saroar** [pointfreeco/swift-composable-architecture#1321] opened 2022-08-31 14:02 UTC
### Description

https://github.com/AddaMeSPB/AddaMeIOS/blob/siteRouter/AddameSPM/Sources/TabsView/TabsReducer.swift#L173

I am thinking the reason its not update becz I am using ObjectId(MongoDB_ID like UUID)

my models look like this 

```
var conversations: IdentifiedArrayOf<ConversationOutPut>
public struct ConversationOutPut: Identifiable {
    public var id: ObjectId
    .........
}

public struct MessageItem: Identifiable {

    public var id: ObjectId? = nil
    public var conversationId: ObjectId
    ..........
}
````

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior
<img width="844" alt="Screenshot 2022-08-31 at 16 49 14" src="https://user-images.githubusercontent.com/8770772/187697998-d7883215-0bf6-4e11-a035-1b9543b86db4.png">

### Actual behavior

`state.conversations.conversations[id: messageResponse.conversationId]` give me nil value 
but when I am use this algorithm 
`state.conversations.conversations .last(where: { $0.id == messageResponse.conversationId })`
I get value

### The Composable Architecture version information

0.39.1

### Destination operating system

iOS 15

### Xcode version information

Version 13.4.1 (13F100)

### Swift Compiler version information

```shell
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by stephencelis** [comment] 2022-08-31 14:46
@saroar Have you determined if this is a bug in TCA or IdentifiedCollections, and if so can you provide a small reproduction for us to work with? Maybe a failing tests?

It does look like `ObjectId` should work based off a simple test:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/658/187707512-982bd220-944d-4b37-968a-ba8a8fc14872.png">

One thing that stands out in your code as odd is that `MessageItem`'s `id` can be `nil`. If it's not a bug and more a question of usage, let me know and I'll convert this to a discussion.

**Comment by saroar** [comment] 2022-08-31 14:48
thanks for quick reply but I am dont understand why this pc of code getting 
`state.conversations.conversations[id: messageResponse.conversationId] = nil`
and this one I get values 
`state.conversations.conversations .last(where: { $0.id == messageResponse.conversationId })`

is not same are same ?

**Comment by saroar** [comment] 2022-08-31 14:51
ok I will write test and let you know as I love to write test with TCA :)

**Comment by stephencelis** [comment] 2022-08-31 14:57
@saroar I can really only speculate without a reproduction to work with. But `IdentifiedArray` wraps a `OrderedDictionary<ID, Identifiable>` with the precondition that `ID` and `Identifiable.id` are the same value at each entry. It sounds like that precondition may not hold for your state, though.

**Comment by saroar** [comment] 2022-09-01 08:15
now I fixed issue it my own issue but my view was not updated 'Conversations last message not update on view' before was working with older version :(

**Comment by stephencelis** [comment] 2022-09-05 17:56
@saroar Were you able to track down the issue? It sounds like you fixed one aspect of it? Did you determine if it's a bug in TCA, Identified Collections, or your application?

**Comment by stephencelis** [comment] 2022-09-08 21:33
@saroar I'm going to close this for now, since we don't have a repro to work with. If you do think there's a bug, please share a repro! Ideally a test case or small project demonstrating the issue. If the bug is with `IdentifiedArray`, please file it in the Identified Collections project, or if it's a bug in TCA, you can open a new issue here.

**Closed by stephencelis** 2022-09-08 21:33 UTC
Labels: bug

**Comment by saroar** [comment] 2022-09-09 13:07
hi this is repo https://github.com/AddaMeSPB/AddaMeIOS/blob/siteRouter/AddameSPM/Sources/TabsView/TabsReducer.swift#L173

**Comment by stephencelis** [comment] 2022-09-09 14:08
@saroar Is it possible for you to provide a small reproduction directly in the Identified Collections library (as a failing test in a PR, perhaps)? I'm not sure how to get your entire application running or what the steps are to reproduce the issue, so a minimized reproduction would be super helpful.
