### ISSUE TITLE
Store not updating - SwiftUI iOS 14 TabView

### ISSUE THREAD

**Issue by asos-danieltavares** [pointfreeco/swift-composable-architecture#227] opened 2020-07-11 19:53 UTC
**Describe the bug**
For some reason store updates are not propagating if a view is inside a `TabView`

**To Reproduce**
```swift
// Works
WindowGroup {
	ResultsView(store: store)
}
```
```swift
// Computer says no
WindowGroup {
	TabView {
		ResultsView(store: store)
		ContentView()
	} .tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
}
```

**Expected behavior**
Store updates should work

**Environment**
 - Xcode: Version 12.0 beta 2 (12A6163b)
 - Swift: 5.3
 - OS: iOS 14

**Additional context**
I have tried passing store and using `WithViewStore` and also having keeping a reference to view store via `@ObservedObject`

**Comment by asos-danieltavares** [comment] 2020-07-11 20:12
@mbrandonw @stephencelis 
Interesting... Adding `.id(UUID())` makes it work
```swift
@main
struct MyApp: App {
	let store: Store<AppState, AppAction>
	@ObservedObject var viewStore: ViewStore<AppState, AppAction>
	init() {
		self.store = Store(
			initialState: AppState(),
			reducer: appReducer,
			environment: AppEnvironment.live
		)
		self.viewStore = ViewStore(store)
	}
	var body: some Scene {
		WindowGroup {
			TabView {
				ResultsView(viewStore: viewStore)
				ContentView()
			}
			.id(UUID())
			.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
			.onAppear {
				viewStore.send(.didFinishLaunching)
			}
		}
	}
}
```

**Comment by mbrandonw** [comment] 2020-07-13 12:03
Hey @asos-danieltavares, thanks for the report!

Is there a reason you are passing the `viewStore` to `ResultsView` instead of just the `store`? I think typically you do not want to do this because you want each view to set up its own observation of the state (via `WithViewStore` or `@ObservedObject`). Perhaps we should even include some documentation on this.

Beyond that, are you able to reproduce this bug in a full code snippet that we can run locally? I had trouble reconstructing the problem.

**Comment by asos-danieltavares** [comment] 2020-07-14 07:12
@mbrandonw I've rejjigged come code around and it started working. Must of been my setup. I think a documentation around the viewStore/store will be great. I have been using it for a while and it's the one thing that I usually miss :). Will keep you informed if I see any more bugs (or my dodgy programming). Cheers

**Comment by asos-danieltavares** [comment] 2020-07-14 07:57
I've managed to replicate it 100% now. I've attached the project.

**Some notes:**
The culprit seems to be `.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))`

As soon as you add that, everything breaks.

```swift
// Keeping an id for the viewstore seems the only way to update things and get things working correctly
.id(viewStore.id)
.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
```

```swift
// This combo works, but any further updates to the store in later tabs will re-draw everything.
.id(UUID())
.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
```

```swift
// Adding the below breaks it
.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
```

[TabViewBug.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4917325/TabViewBug.zip)

**Comment by stephencelis** [comment] 2020-07-22 19:01
Hey @asos-danieltavares thanks for reopening with a repro! We'll try to take a look at this soon.

**Comment by stephencelis** [comment] 2020-09-07 17:19
Looks like this is another SwiftUI bug unrelated to TCA. A vanilla repro: https://gist.github.com/stephencelis/ee80fec9be7c7626012d3d005c8f712b

Wrapping your `NumberView` in a `VStack` seems to fix things:

```swift
TabView {
  VStack { NumbersView(store: store) }
  Text("View 2")
  Text("View 3")
}
```

**Comment by stephencelis** [comment] 2020-09-07 17:20
Gonna close this out since it's another thing out of our control. Hopefully some of these bugs get fixed before the beta cycle finishes!

**Closed by stephencelis** 2020-09-07 17:20 UTC
Labels: apple bug
