### ISSUE TITLE
testScopeWithPublisherTransform, testPublisherScope and testIfLetAfterScope fail in Xcode 12 beta 6

### ISSUE THREAD

**Issue by andreyz** [pointfreeco/swift-composable-architecture#269] opened 2020-08-27 10:43 UTC
**Describe the bug**
Noticed that `IfLet` on parent store stopped calling `else` clause on the optional state switching back to `nil`. 
After I run the tests and 3 of them failed.

**To Reproduce**
Run the tests. Run UIKitCaseStudies and click through LoadThenNavigate, it fails to show CounterView correctly.

**Expected behavior**
`IfLet` on parent store calls `else` clause on the optional state switching back to `nil`.
Tests pass.

**Environment**
 - Xcode 12 beta 6
 - Swift 5.3
 - OS iOS 14 beta 6

**Additional context**
```
Test: testIfLetAfterScope() in StoreTests failed in Test Scheme Action on iPhone 11 Pro
Assertions: Assertion Failure at StoreTests.swift:299: XCTAssertEqual failed: ("[nil, nil, Optional(1)]") is not equal to ("[nil, Optional(1)]")
File: StoreTests.swift:299

Assertions: Assertion Failure at StoreTests.swift:302: XCTAssertEqual failed: ("[nil, nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil]")
File: StoreTests.swift:302

Assertions: Assertion Failure at StoreTests.swift:305: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1)]")
File: StoreTests.swift:305

Assertions: Assertion Failure at StoreTests.swift:308: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil]")
File: StoreTests.swift:308

Assertions: Assertion Failure at StoreTests.swift:311: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil, Optional(1)]")
File: StoreTests.swift:311

Assertions: Assertion Failure at StoreTests.swift:314: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil, Optional(1), nil]")
File: StoreTests.swift:314

  Assertions: Assertion Failure at StoreTests.swift:299: XCTAssertEqual failed: ("[nil, nil, Optional(1)]") is not equal to ("[nil, Optional(1)]")
  File: StoreTests.swift:299

  Assertions: Assertion Failure at StoreTests.swift:302: XCTAssertEqual failed: ("[nil, nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil]")
  File: StoreTests.swift:302

  Assertions: Assertion Failure at StoreTests.swift:305: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1)]")
  File: StoreTests.swift:305

  Assertions: Assertion Failure at StoreTests.swift:308: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil]")
  File: StoreTests.swift:308

  Assertions: Assertion Failure at StoreTests.swift:311: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil, Optional(1)]")
  File: StoreTests.swift:311

  Assertions: Assertion Failure at StoreTests.swift:314: XCTAssertEqual failed: ("[nil, nil, Optional(1), nil, Optional(1), nil, Optional(1)]") is not equal to ("[nil, Optional(1), nil, Optional(1), nil, Optional(1), nil]")
  File: StoreTests.swift:314

Test: testPublisherScope() in StoreTests failed in Test Scheme Action on iPhone 11 Pro
Assertions: Assertion Failure at StoreTests.swift:255: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
File: StoreTests.swift:255

Assertions: Assertion Failure at StoreTests.swift:258: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
File: StoreTests.swift:258

Assertions: Assertion Failure at StoreTests.swift:260: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
File: StoreTests.swift:260

Assertions: Assertion Failure at StoreTests.swift:262: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
File: StoreTests.swift:262

Assertions: Assertion Failure at StoreTests.swift:264: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
File: StoreTests.swift:264

  Assertions: Assertion Failure at StoreTests.swift:255: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
  File: StoreTests.swift:255

  Assertions: Assertion Failure at StoreTests.swift:258: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
  File: StoreTests.swift:258

  Assertions: Assertion Failure at StoreTests.swift:260: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
  File: StoreTests.swift:260

  Assertions: Assertion Failure at StoreTests.swift:262: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
  File: StoreTests.swift:262

  Assertions: Assertion Failure at StoreTests.swift:264: XCTAssertEqual failed: ("[0, 0]") is not equal to ("[0, 1]")
  File: StoreTests.swift:264

Test: testScopeWithPublisherTransform() in StoreTests failed in Test Scheme Action on iPhone 11 Pro
Assertions: Assertion Failure at StoreTests.swift:116: XCTAssertEqual failed: ("["0", "0"]") is not equal to ("["0", "1"]")
File: StoreTests.swift:116

Assertions: Assertion Failure at StoreTests.swift:118: XCTAssertEqual failed: ("["0", "0"]") is not equal to ("["0", "1"]")
File: StoreTests.swift:118

Assertions: Assertion Failure at StoreTests.swift:120: XCTAssertEqual failed: ("["0", "0", "1"]") is not equal to ("["0", "1", "2"]")
File: StoreTests.swift:120

  Assertions: Assertion Failure at StoreTests.swift:116: XCTAssertEqual failed: ("["0", "0"]") is not equal to ("["0", "1"]")
  File: StoreTests.swift:116

  Assertions: Assertion Failure at StoreTests.swift:118: XCTAssertEqual failed: ("["0", "0"]") is not equal to ("["0", "1"]")
  File: StoreTests.swift:118

  Assertions: Assertion Failure at StoreTests.swift:120: XCTAssertEqual failed: ("["0", "0", "1"]") is not equal to ("["0", "1", "2"]")
  File: StoreTests.swift:120
```

**Comment by andreyz** [comment] 2020-08-27 10:58
Interesting bit of trivia, for 0.6.0 only `testScopeWithPublisherTransform` fails.

**Comment by stephencelis** [comment] 2020-08-27 13:54
@andreyz I'm having trouble reproducing locally. Those were failing in beta 4 due to a bug that seems to have been fixed in later betas. You've checked the repo out and are running on an iOS 14 sim?

**Comment by andreyz** [comment] 2020-08-27 14:29
Yes and yes. Checked out main and running on iOS 14 beta 6 simulator.

**Comment by stephencelis** [comment] 2020-08-27 15:22
Oh huh. I'd been building for macOS on Catalina, so it looks like this is a bug introduced in Big Sur and iOS 14. I've pushed a fix that should be vetted by CI here: https://github.com/pointfreeco/swift-composable-architecture/pull/266

Thanks for the report!

**Comment by andreyz** [comment] 2020-08-27 16:39
Thanks for amazing library and swift response.

**Comment by stephencelis** [comment] 2020-08-27 17:35
Should be fixed on the main branch!

**Closed by stephencelis** 2020-08-27 17:35 UTC
