### ISSUE TITLE
TicTacToe example bug

### ISSUE THREAD

**Issue by augard** [pointfreeco/swift-composable-architecture#259] opened 2020-08-18 16:16 UTC
**Describe the bug**
TicTacToe UIKit version is crashing after tapping quit game button

```swift
Fatal error: "GameAction.quitButtonTapped" was received by an optional reducer when its state was "nil". This can happen for a few reasons:

* The optional reducer was combined with or run from another reducer that set "GameState" to "nil" before the optional reducer ran. Combine or run optional reducers before reducers that can set their state to "nil". This ensures that optional reducers can handle their actions while their state is still non-"nil".

* An active effect emitted this action while state was "nil". Make sure that effects for this optional reducer are canceled when optional state is set to "nil".

* This action was sent to the store while state was "nil". Make sure that actions for this reducer can only be sent to a view store when state is non-"nil". In SwiftUI applications, use "IfLetStore".: file /Users/lukas/Downloads/swift-composable-architecture-main 3/Examples/TicTacToe/Sources/Core/NewGameCore.swift, line 28
2020-08-18 18:13:55.107490+0200 TicTacToe[81993:888831] Fatal error: "GameAction.quitButtonTapped" was received by an optional reducer when its state was "nil". This can happen for a few reasons:

* The optional reducer was combined with or run from another reducer that set "GameState" to "nil" before the optional reducer ran. Combine or run optional reducers before reducers that can set their state to "nil". This ensures that optional reducers can handle their actions while their state is still non-"nil".

* An active effect emitted this action while state was "nil". Make sure that effects for this optional reducer are canceled when optional state is set to "nil".

* This action was sent to the store while state was "nil". Make sure that actions for this reducer can only be sent to a view store when state is non-"nil". In SwiftUI applications, use "IfLetStore".: file /Users/lukas/Downloads/swift-composable-architecture-main 3/Examples/TicTacToe/Sources/Core/NewGameCore.swift, line 28
```

**Comment by mbrandonw** [comment] 2020-08-18 16:39
Can you confirm which version of Xcode you are using? Is this in the Xcode 12 beta?

I'm unable to reproduce this in Xcode 11.6, but I do see some strange behavior in the Xcode beta and we should definitely look into it soon.

**Comment by augard** [comment] 2020-08-19 07:46
Ah sorry, thats true, i was using Xcode 12 beta.

**Comment by stephencelis** [comment] 2020-08-31 17:21
@augard Was gonna look into this today but I can't reproduce in Xcode 12 beta 6. Can you try again?

**Comment by stephencelis** [comment] 2020-09-07 16:34
@augard I'm gonna close this out since it seems to be fixed, both in Xcode 11 and the latest Xcode 12 beta. Please reopen if you can reproduce, though!

**Closed by stephencelis** 2020-09-07 16:34 UTC
