### ISSUE TITLE
Cannot build the current version with CI, ComputeTargetDependencyGraph

### ISSUE THREAD

**Issue by stachurski2** [pointfreeco/swift-composable-architecture#3254] opened 2024-07-24 14:35 UTC
### Description

Hello, 
While building app on CI (dev-azure agent), with Xcode 15.4 on Mac OS Sonoma, I got the hazy error 
``
The following build commands failed:[0m
ComputeTargetDependencyGraph[0m
``
It occurs for my project, solely if swift-composable-architecture is added. I try to build my app with version 1.12 of swift-composable-architecture. 
Otherwise, locally everything seems to work fine.  

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The library is expected to build while project compilation

### Actual behavior

Building of my project fails, due to :
 ``
The following build commands failed:[0m
ComputeTargetDependencyGraph[0m
``

### Steps to reproduce

Just archive the app.
![Screenshot 2024-07-24 at 16 10 03](https://github.com/user-attachments/assets/0a6523da-1c45-42fe-95ce-02e3ce75feed)

### The Composable Architecture version information

1.12

### Destination operating system

iOS 17.5

### Xcode version information

Xcode 15.4

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
```

**Comment by stephencelis** [comment] 2024-07-24 14:45
@stachurski2 Without a repro I'm not sure we can consider this a bug. Can you share a minimal project that reproduces the issue?

It looks like many of the packages are on the latest version. Does your project check in its Package.resolved file? Generally you want to check this file in to maintain a stable CI environment.

**Comment by stachurski2** [comment] 2024-07-24 16:10
Thank you for the response @stephencelis  

Actually, It started occurring with version 1.2, but attempts of update didn't help. I can share my Package.resolved file.  My project doesn't check it, I updated it with Xcode manually (by click `Update to latests package version` locally) 
[Package.json](https://github.com/user-attachments/files/16364789/Package.json)

**Comment by funkyboy** [comment] 2024-07-24 17:10
Seems suspiciously similar to https://github.com/pointfreeco/swift-composable-architecture/issues/3255 but not sure.

**Comment by stephencelis** [comment] 2024-07-24 20:03
@stachurski2 Can you try updating and reresolving your dependencies again to see if it's fixed? We just rolled out new versions of dependencies that stick with the original package URL and it seems to help in the remaining problematic situations we know of.

**Comment by stachurski2** [comment] 2024-07-25 09:54
Hello @stephencelis , 
I tried to update to latest version, unfortunately without success. I got more logs, I believe they could be helpful:
[log.txt](https://github.com/user-attachments/files/16373995/log.txt)

The one part is concerning me:

<img width="802" alt="Screenshot 2024-07-25 at 11 53 46" src="https://github.com/user-attachments/assets/96645e2d-274a-437b-bf0b-610db9ddaea5">


Thank you!

**Comment by mbrandonw** [comment] 2024-07-25 16:04
Hi @stachurski2, in the logs it shows you that you haven't enabled macros for a few targets:

```
2024-07-25T08:00:08.0303060Z /Users/runner/Library/Developer/Xcode/DerivedData/hex-gtcfwfcderxelgcaptdveijcpwfx/SourcePackages/checkouts/swift-composable-architecture/Package.swift:PACKAGE-TARGET:ComposableArchitectureMacros: error: Target 'ComposableArchitectureMacros' must be enabled before it can be used.
2024-07-25T08:00:08.0306530Z /Users/runner/Library/Developer/Xcode/DerivedData/hex-gtcfwfcderxelgcaptdveijcpwfx/SourcePackages/checkouts/swift-case-paths/Package.swift:PACKAGE-TARGET:CasePathsMacros: error: Target 'CasePathsMacros' must be enabled before it can be used.
2024-07-25T08:00:08.0310750Z /Users/runner/Library/Developer/Xcode/DerivedData/hex-gtcfwfcderxelgcaptdveijcpwfx/SourcePackages/checkouts/swift-dependencies/Package.swift:PACKAGE-TARGET:DependenciesMacrosPlugin: error: Target 'DependenciesMacrosPlugin' must be enabled before it can be used.
```

Hopefully once you do that it will build just fine.

**Comment by mbrandonw** [comment] 2024-07-25 18:38
I think this issue has now been fixed so I am going to close this out. Please feel free to open a discussion if you have more questions!

**Closed by mbrandonw** 2024-07-25 18:38 UTC
Labels: bug

**Comment by stachurski2** [comment] 2024-07-25 23:44
Hello there, 
Adding `-skipMacroValidation` to xcodebuild invocation resolves the problem.
Regards and thank you, 
Stan
