### ISSUE TITLE
Composable Architecture swift pm on Xcode 12.5 playground

### ISSUE THREAD

**Issue by BeerPoldet** [pointfreeco/swift-composable-architecture#521] opened 2021-04-30 04:30 UTC
**Describe the bug**
Composable Architecture swift pm doesn't compile when it's imported in Xcode 12.5 playground. When this happens. It causes other targets that rely on TCA to also not compile.

**To Reproduce**
[TestSwiftPMPlayground.zip](https://github.com/pointfreeco/swift-composable-architecture/files/6402970/TestSwiftPMPlayground.zip)

```swift
import UIKit
import ComposableArchitecture // << No such module 'ComposableArchitecture'

var greeting = "Hello, playground"
```

**Expected behavior**
Even though, Compiling targets with Xcode 12.5 play button do work perfectly fine. I also want this to work on Playground as well.

**Screenshots**
<img width="796" alt="Screen Shot 2564-04-30 at 11 21 23" src="https://user-images.githubusercontent.com/7531231/116648149-8cfd2e00-a9a6-11eb-8b65-04415fde25ee.png">
<img width="793" alt="Screen Shot 2564-04-30 at 11 19 22" src="https://user-images.githubusercontent.com/7531231/116648169-92f30f00-a9a6-11eb-882b-bea2dd6baaa7.png">

**Environment**
 - Xcode 12.5
 - Swift 5.4
 - OS 14.5

**Additional context**
I thought this wasn't specific problem to Composable Architecture. Then I tried again but replace TCA with `swift-prelude`. Playground does work fine. So I think I have a conclusion.

**Comment by andreyz** [comment] 2021-04-30 04:57
This also happened in my workspace with a playground inside a package. Though, I'm not as sure that this is caused by TCA, try NutritionalFacts playground inside Apple's Fruita sample project — it'll probably fail too. Seems like an SPM + Xcode 12.5 issue. 

What helped is seems like magical combination of Swift Package Manager > Resolve Required, Swift Package Manager > Update to Latest Versions. And possibly an Xcode restart.

One clue as to what's going on, is to check the diff on Packages.resolved and you'll probably see Xcode removing TCA for some reason. Doing the Resolve/Update cycle will return TCA back to that file.

**Comment by BeerPoldet** [comment] 2021-04-30 05:23
@andreyz Thanks for replying.
I have tried SPM + Xcode 12.5 with an other package which is `swift-prelude` which is other than TCA. It works just fine.

I've  also tried your suggestions. None of them work. 

PS. Appreciate your help.

**Comment by andreyz** [comment] 2021-04-30 14:24
If you care to zip your project and share, I can try debugging it for you. The issue can be caused by the project's structure, dependencies configuration, Package.swift product definitions (version/branch/etc)...

**Comment by BeerPoldet** [comment] 2021-04-30 15:03
Here you go
https://github.com/pointfreeco/swift-composable-architecture/files/6402970/TestSwiftPMPlayground.zip

**Comment by andreyz** [comment] 2021-05-01 19:11
Gave it a fair try ⬆️ and I couldn't make the playground work either.

**Comment by lukeredpath** [comment] 2021-05-04 13:25
I'm also running into this problem.

**Comment by andreyz** [comment] 2021-05-04 14:56
@lukeredpath I can confirm exact same error description, failed CasePaths import.

**Comment by BeerPoldet** [comment] 2021-06-03 04:12
Any updates?

**Comment by stephencelis** [comment] 2021-07-07 22:03
> Here you go
> https://github.com/pointfreeco/swift-composable-architecture/files/6402970/TestSwiftPMPlayground.zip

I was able to get this working just fine in Xcode 13b2.

- Opened project
- Built library
- Navigated to playground
- Ran playground ("Build Active Scheme" was checked)

And although "No such module 'ComposableArchitecture'" renders next to the import, it appears to be a bug in Xcode, and the `greeting` line prints `"Hello, playground"` in the gutter.

I'm going to close this out since it seems to be an Apple tooling bug, and not something specific to TCA. A few ways to go from here:

- File feedback with Apple if you can, the more we can do to improve Xcode's tooling, the better! We try to file feedback often for the issues we encounter
- Start a discussion on the Swift forums about the issue, which might get some Apple eyes on the problem, or get some more tips for working around these quirks
- You could also start a discussion on the GitHub forums here, where folks may have encountered the same issue with the library

If anyone is able to gather evidence that TCA is structured in a way that causes particular problems for Xcode playgrounds over other projects, and if there are things we can do to improve that, we'd love to know! You can keep us posted in this issue, or in a new one.

**Closed by stephencelis** 2021-07-07 22:03 UTC
