### ISSUE TITLE
Newly created project cannot compile

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [pointfreeco/swift-composable-architecture#1820] opened 2023-01-11 08:46 UTC
### Description

I am trying to use this library in a a newly created SwiftUI project and when I import the library, the code refuses to compile due to the following error `'Width' is not a member type of struct 'SwiftUI.Font'`

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The code compiles without errors.

### Actual behavior

The code does not compile with the error: `'Width' is not a member type of struct 'SwiftUI.Font'` in the `TextState.swift` file.

### Steps to reproduce

1. Create a new SwiftUI project
2. Import the `swift-composable-architecture` package
3. Compile the project

### The Composable Architecture version information

0.49.2

### Destination operating system

iOS 15

### Xcode version information

14.1 beta (14B5024h)

### Swift Compiler version information

```shell
swift-driver version: 1.62.14 Apple Swift version 5.7.1 (swiftlang-5.7.1.131.4 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
```

**Comment by tgrapperon** [comment] 2023-01-11 14:08
Hey @alvarezGarciaMarcos! I'm unable to reproduce the issue. Would it be possible to attach a project where it fails to build?
BTW, Xcode's current version is 14.2, so I'd try updating Xcode too.

**Comment by alvarezGarciaMarcos** [comment] 2023-01-12 21:43
Thank you @tgrapperon for the heads up! It turns out that upgrading the Xcode version fixed the issue, I am not really sure why, but it does now work.

**Comment by mbrandonw** [comment] 2023-01-12 22:10
Thanks for updating this @alvarezGarciaMarcos, I'm going to close the issue since it doesn't seem to be a problem with the library.

**Closed by mbrandonw** 2023-01-12 22:10 UTC
Labels: bug
