### ISSUE TITLE
`ViewStore.binding` firing when state is nil

### ISSUE THREAD

**Issue by ferologics** [pointfreeco/swift-composable-architecture#625] opened 2021-06-30 10:43 UTC
When a view is dismissed, and the parent nils the child's state, an `optional()` reducer will receive actions from child's view binding even if the child state is `nil`, thus we get an `assertionFailure`. How to prevent that? 

Could the `IfLetStore` somehow remove the view immediately when it's optional state is set to nil (to not leave room for any child state action emission)?

**Comment by stephencelis** [comment] 2021-06-30 14:01
:wave: @ferologics Thanks for the report. We'd love to help but need a bit more info. When you tap the "new issue" button we have a "bug report" template that tries to collect a bunch of info that make it easier for us to get a handle on issues. The most helpful things would be:

- Could you attach a project demonstrating the problem?
- Could you let us know what version of swift-composable-architecture, Xcode, OS, etc., the problem is occurring in? OS behavior changes over time (SwiftUI 1 vs. 2 vs. 3), so it'd be helpful to know if this is a long-standing issue, new, etc.

**Comment by stephencelis** [comment] 2021-07-07 19:14
Hi @ferologics, I'm going to close this now, since there's not enough information to reproduce. If either of the other issues that mention this one, #631 or #634, are the same issue, please let us know! And if it's an entirely different issue, please attach a project that captures it here. We'd love to figure out a fix! I'll reopen this if you do.

**Closed by stephencelis** 2021-07-07 19:14 UTC

**Comment by stephencelis** [comment] 2021-07-07 22:09
(This might also be a related issue: https://github.com/pointfreeco/swift-composable-architecture/issues/282)

**Comment by ferologics** [comment] 2021-08-19 10:58
@stephencelis I'm apologize for the lack of documentation provided around the issue. During my debugging I've found that the `assertionFailure was triggered from within a `GeometryReader` of the child view (who's state was nil at the time). The `GeometryReader` updates a binding passed from parent to child, which would re-evaluate upon the child's view dismissal.

At the end of the day we still had to use a `[ID:State]` dictionary (which kept the state "alive" in case any actions would be sent to it). Perhaps some may use this as an alternative to `optional(breakpointOnNil: false)` (although I would not encourage it).
