### ISSUE TITLE
Different result in debug and release builds

### ISSUE THREAD

**Issue by lukeleleh** [pointfreeco/swift-composable-architecture#1086] opened 2022-05-08 17:36 UTC
**Describe the bug**
Hello! I made a simple game app using TCA and I liked the experience, really amazing and enjoyable! Thank you 🙌

However, I tried the first TestFlight build on my device and for my surprise, the app was not working properly so I thought it had something to do with the release build configuration because in the debug one, everything works properly. I run the app using the release build configuration in Xcode and I experienced the same (as in TestFlight). Checking what could cause this, I tried some things like turning off the Release compiler optimizations, putting the same configuration of the debug build to the release, etc but no luck at all. I have a parent/app reducer that is composed simply by another reducer (using pullback) and debugging, in the debug configuration, I hit breakpoints in both reducers but in the release one, only in the parent/app reducer.

I put a breakpoint in the pullback method [here](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/Reducer.swift#L276) and if I checked correctly, it seems that in the debug build configuration, the guard statement passes but in the release one, it doesn’t, so the local action cannot be extracted from the global one. In my case, I’m not receiving any message in the console or experiencing a crash. It’s simply a different output in terms of functionality for debug and release builds.

**To Reproduce**
I managed to reproduce the same issue creating a small sample app! If I run the app in the Debug build configuration, everything works as expected, where the settings screen opens. However, if I go the the apps’s scheme and change the build configuration to Release, the settings screen doesn’t open (Check Screenshots section).

[Debug Release.zip](https://github.com/pointfreeco/swift-composable-architecture/files/8647470/Debug.Release.zip)

**Expected behavior**
Have the same output in terms of functionality for debug and release builds.

Also, I found that if I remove everything related to the binding stuff (`BindableState`, `BindableAction`, etc) in the settings reducer, the settings screen is opened as expected in the release build configuration!

**Screenshots**
Debug           |  Release
:-------------------------:|:-------------------------:
<video width="480" alt="Debug" src="https://user-images.githubusercontent.com/18327422/167307983-d93d473e-74f4-4897-97e6-047683c5363b.mp4">|<video width="480" alt="Release" src="https://user-images.githubusercontent.com/18327422/167307981-de246135-1ba6-493a-8712-f8bc065be2cb.mp4">

**Environment**
  - swift-composable-architecture version [0.34.0]
  - Xcode [13.3.1 but I tried also with 13.2.1 and happens the same]
  - Swift [5.6]
  - OS [iOS 15]

**Additional context**
If someone is facing the same issue, a workaround is to stop using the binding stuff (`BindableState`, `BindableAction`, etc) and go for having an action that represents the updates from the view.

**Comment by tgrapperon** [comment] 2022-05-08 19:07
Thanks for the report @lukeleleh!
It seems the issues comes from your 1-case `AppAction` enum:
```swift
public enum AppAction: Equatable {
  case menu(MenuAction)
}
```
If you add one case to it, it works as expected:
```swift
public enum AppAction: Equatable {
  case menu(MenuAction)
  case noop
}
```
I don't really have the time to go deeper. When you press the "Setting" button, the store receives the action, but the reducer's code isn't executed for this action. The strange thing is that is is executed when you tap the very symmetric "Leaderboard" button.

My guess is that, for some reason, `swift-case-paths` fails to extract the action in this configuration and the store doesn't address it to the reducer. There's a lot of internal runtime magic with this library, and it is possible that you hit a new edge case with 1-case enums in Release mode. I'll try to extract a sub-sample of the issue, but if the problem comes from there, fixing it would be way beyond by competency in Swift.

As an aside, you did store your store instance as one of your `RootView` property. I would advise to either declare it at the top level, or use a `@State var store = Store(…` to preserve the instance in any case `RootView` is recreated by `WindowGroup`. It shouldn't happen, but if does for some internal reason, your whole app state will be renitialized.

**Comment by tgrapperon** [comment] 2022-05-08 19:42
@lukeleleh, I've just noted that your `SettingAction` is a `BindableAction` and `LeaderBoardAction` isn't. I don't think this is the root of the issue: I'm able to reproduce the problem whenever one of the associated values of `SettingsActions` is (or contains) `Any`. In the case of `Binding`, it comes from the `value: Any` storage, but you can use any struct that contains some `Any` (or `Any` directly as an associated value), and the issue appears. 
For example: 
```SettingsActions {
  case onAppear
  case issue(Any)
}
```
It really looks like something connected to the way things are stored and the ability to extract `Actions` from their parent. Maybe the issue comes more from `Any` than being a 1-case enum (or both), and maybe you removing `Bindings` or me adding a `noop` case to `AppAction` were enough to nudge the issue in the right direction.

I'll try to build a small sample case for further investigation, but it really looks connected to `swift-case-paths`.

CC/ @stephencelis

**Comment by tgrapperon** [comment] 2022-05-08 20:20
I'm able to reproduce the issue in `swift-case-path` and I've opened [an issue](https://github.com/pointfreeco/swift-case-paths/issues/71) there accordingly.

**Comment by lukeleleh** [comment] 2022-05-09 18:37
Thank you a lot for your help @tgrapperon, for opening an issue in `swift-case-path` and also for the `RootView` store advise! 🙌

**Comment by stephencelis** [comment] 2022-07-07 21:06
I'm going to close this since we're tracking it in Case Paths. Thanks again @tgrapperon for investigating!!

**Closed by stephencelis** 2022-07-07 21:06 UTC
